Repository WordPress/wporg-main-2022, pull requests merged in 2022-09, with the labels that each got.

#108 Allow post content edits to be viewed by Editors
  source/wp-content/mu-plugins/theme-switcher.php
Labels: [Component] Tools, [Component] Backend

#113 Block: Add "Random Headings" block
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/patterns/front-page.php
  source/wp-content/themes/wporg-main-2022/src/random-heading/block.json
  source/wp-content/themes/wporg-main-2022/src/random-heading/edit.js
  source/wp-content/themes/wporg-main-2022/src/random-heading/index.js
  source/wp-content/themes/wporg-main-2022/src/random-heading/index.php
  source/wp-content/themes/wporg-main-2022/src/random-heading/style.scss
  source/wp-content/themes/wporg-main-2022/style.css
Labels: [Component] Blocks

#116 Fix export context bug
  env/refresh.sh
  source/wp-content/mu-plugins/theme-switcher.php
Labels: [Component] Tools, [Component] Backend

#118 Try parsing block content and replacing strings with i18n functions
  env/build-patterns.sh
  env/export-content.php
  env/export-content/includes/parser.php
  env/export-content/includes/parsers/BasicText.php
  env/export-content/includes/parsers/BlockParser.php
  env/export-content/includes/parsers/Button.php
  env/export-content/includes/parsers/Heading.php
  env/export-content/includes/parsers/Noop.php
  env/export-content/includes/parsers/Paragraph.php
  env/export-content/includes/parsers/ShortcodeBlock.php
  env/export-content/includes/parsers/TextNode.php
  env/export-content/includes/utils.php
  env/export-content/index.php
  phpcs.xml
  source/wp-content/themes/wporg-main-2022/patterns/download.php
  source/wp-content/themes/wporg-main-2022/patterns/home.php
Labels: [Component] Theme, [Component] Tools, i18n

#119 Add a new Designer role & permission checks
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/inc/capabilities.php
Labels: [Component] Backend

#125 Add RTLCSS support
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/package.json
  source/wp-content/themes/wporg-main-2022/src/download/index.js
  source/wp-content/themes/wporg-main-2022/src/download/style.scss
  source/wp-content/themes/wporg-main-2022/src/style/block.json
  source/wp-content/themes/wporg-main-2022/src/style/index.js
  source/wp-content/themes/wporg-main-2022/src/style/style.scss
  source/wp-content/themes/wporg-main-2022/style.css
  source/wp-content/themes/wporg-main-2022/webpack.config.js
  yarn.lock
Labels: [Component] Tools, i18n
