Repository WordPress/wporg-main-2022, pull requests merged in 2022-08, with the labels that each got.

#33 Improve setup
  package.json
  readme.md
Labels: [Component] Tools

#38 Templates: Remove top-level block gap spacing in page content
  source/wp-content/themes/wporg-main-2022/templates/front-page.html
  source/wp-content/themes/wporg-main-2022/templates/page-download.html
Labels: [Component] Theme

#39 Prevent arrow characters from becoming emoji
  source/wp-content/themes/wporg-main-2022/functions.php
Labels: [Component] Backend

#35 Allow wp-cli to regenerate the .htaccess file
  .wp-env.json
  env/setup.sh
  wp-cli.local.yml
Labels: [Component] Tools

#34 Add meta descriptions
  env/import-content.php
  package.json
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/inc/page-meta-descriptions.php
Labels: [Component] Backend

#47 Add download modal
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/package.json
  source/wp-content/themes/wporg-main-2022/src/components/download-modal/DownloadModal.js
  source/wp-content/themes/wporg-main-2022/src/components/download-modal/index.js
  source/wp-content/themes/wporg-main-2022/src/index.js
  source/wp-content/themes/wporg-main-2022/style.css
  yarn.lock
Labels: [Component] Blocks, [Component] Theme

#60 Theme: Override spacing values on small screens
  source/wp-content/themes/wporg-main-2022/style.css
Labels: [Component] Theme

#54 Add hreflang link tags
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/inc/hreflang.php
Labels: [Component] Backend

#64 Theme: Add page content as patterns
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/patterns/download.php
  source/wp-content/themes/wporg-main-2022/patterns/front-page.php
  source/wp-content/themes/wporg-main-2022/templates/front-page.html
  source/wp-content/themes/wporg-main-2022/templates/page-download.html
Labels: [Component] Theme

#62 Disable Jetpack auto-images to reduce query count
  source/wp-content/themes/wporg-main-2022/functions.php
Labels: [Component] Backend

#73 Missing entry-content class
  source/wp-content/themes/wporg-main-2022/templates/front-page.html
  source/wp-content/themes/wporg-main-2022/templates/page-download.html
Labels: [Type] Bug, [Component] Theme

#72 Stop lazy loading of content images above the fold to improve LCP
  source/wp-content/themes/wporg-main-2022/functions.php
Labels: [Component] Backend

#75 Add structured content to download page
  source/wp-content/themes/wporg-main-2022/inc/page-meta-descriptions.php
  source/wp-content/themes/wporg-main-2022/inc/shortcodes.php
Labels: [Component] Backend

#86 Update copy for 'Download and install' section
  source/wp-content/themes/wporg-main-2022/patterns/download.php
Labels: [Type] Bug, [Component] Content

#89 Content: Update images for community and editor sections
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/patterns/front-page.php
Labels: [Component] Content

#96 Content: Use the "Dots" style for the download page navigation
  source/wp-content/themes/wporg-main-2022/patterns/download.php
Labels: [Component] Content

#99 Replace community image with compressed version
  source/wp-content/themes/wporg-main-2022/patterns/front-page.php
Labels: [Component] Content

#106 Blocks: Create a stub Download Modal "block"
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/src/components/download-modal/download-modal.js
  source/wp-content/themes/wporg-main-2022/src/components/download-modal/index.js
  source/wp-content/themes/wporg-main-2022/src/download/block.json
  source/wp-content/themes/wporg-main-2022/src/download/index.js
  source/wp-content/themes/wporg-main-2022/src/index.js
Labels: [Component] Blocks

#100 Build pattern files from post content
  env/build-patterns.sh
  env/export-content.php
  env/page-manifest.json
  package.json
Labels: [Component] Tools, [Component] Backend
