Repository WordPress/wporg-main-2022, pull requests merged in 2022-07, with the labels that each got.

#21 Tools: Add linter workflow for trunk and PRs
  .github/workflows/linters.yml
  source/wp-content/themes/wporg-main-2022/functions.php
Labels: [Component] Tools

#22 Tools: Merge existing content in when syncing from live site.
  env/import-content.php
Labels: [Component] Tools

#25 Force the import script to use a production server
  env/import-content.php
Labels: [Type] Bug, [Component] Tools

#19 Add backstopjs
  .gitignore
  backstop.json
  package.json
  yarn.lock
Labels: [Component] Tools

#26 Add lighthouse scripts
  .gitignore
  package.json
  readme.md
  yarn.lock
Labels: [Component] Tools

#27 Add shortcodes for common dynamic numbers
  env/data.xml
  source/wp-content/themes/wporg-main-2022/functions.php
  source/wp-content/themes/wporg-main-2022/inc/shortcodes.php
Labels: [Component] Theme, [Component] Backend
