Repository WordPress/wporg-main-2022, pull requests merged in 2023-12, with the labels that each got.

#358 Shortcodes: add minimum PHP shortcode
  source/wp-content/themes/wporg-main-2022/inc/shortcodes.php
Labels: [Type] Bug

#359 Add minimum_php shortcode to requirements page
  source/wp-content/themes/wporg-main-2022/patterns/about-requirements.php
Labels: [Component] Theme

#357 Add 2023 SotW banner
  source/wp-content/themes/wporg-main-2022/patterns/home.php
Labels: [Component] Theme, [Status] On Hold

#369 Update homepage logos and add alt text
  source/wp-content/themes/wporg-main-2022/patterns/home.php
Labels: [Type] Enhancement

#368 Add link to Roadmap pattern
  source/wp-content/themes/wporg-main-2022/patterns/about-roadmap.php
Labels: [Type] Enhancement
